---
abstract: 'Perl extention for one time script.'
author:
  - 'Masayuki Matsuki E<lt>y.songmu@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Script-Ichigeki
no_index:
  directory:
    - inc
provides:
  Script::Ichigeki:
    file: lib/Script/Ichigeki.pm
    version: 0.01
  Script::Ichigeki::Hissatsu:
    file: lib/Script/Ichigeki/Hissatsu.pm
    version: 0
requires:
  File::Tee: 0
  IO::Prompt::Simple: 0
  Mouse: 0
  Path::Class: 0
  Time::Piece: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
